# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, Terraform!
  displayName: 'Run a one-line script'

- task: AWSShellScript@1
  displayName: 'Terraform Init'
  inputs:
    awsCredentials: 'sc-demo-lab-aws-tf'
    regionName: 'us-east-1'
    scriptType: 'inline'
    disableAutoCwd: true
    workingDirectory: '$(System.DefaultWorkingDirectory)/demo/configuration/'
    inlineScript: |
      terraform init
      aws sts get-caller-identity

- task: AWSShellScript@1
  displayName: 'Terraform Plan'
  inputs:
    awsCredentials: 'sc-demo-lab-aws-tf'
    regionName: 'us-east-1'
    scriptType: 'inline'
    inlineScript: 'terraform plan -var-file="backend.tfvars"'
    disableAutoCwd: true
    workingDirectory: '$(System.DefaultWorkingDirectory)/demo/configuration/'


- script: |
      pwd
      cd $(System.DefaultWorkingDirectory)/demo/configuration
      ls -lrtha
  displayName: 'Show Terraform files'
