# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, Terraform!
  displayName: 'Run a one-line script'

- task: AWSShellScript@1
  displayName: 'Terraform Init'
  inputs:
    regionName: 'us-east-1'
    scriptType: 'inline'
    disableAutoCwd: true
    workingDirectory: '$(System.DefaultWorkingDirectory)/demo/configuration/'
    inlineScript: |
      terraform init
      
- script: |
      pwd
      cd $(System.DefaultWorkingDirectory)/demo/configuration
      ls -lrth
  displayName: 'Show Terraform files'
